### ISSUE TITLE
windows平台路径解析有问题啊

### ISSUE THREAD

**Issue by keysunHong** [aubdiy/code-generator#3]
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/allWorks/code-generator/target/classes/template/4_spring_boot/resource/application.properties
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at self.aub.product.code.generator.generator.resource.PropertiesGenerator.generateRes(PropertiesGenerator.java:28)
	at self.aub.product.code.generator.Launcher.launch(Launcher.java:49)
	at self.aub.product.code.generator.Launcher.main(Launcher.java:55)

**Comment by aubdiy** [comment]
非常感谢，这个是windows环境问题，linux 和 mac  不会出现，
现在已经修复
